/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as publicLoginRouteImport } from './routes/(public)/login'
import { Route as authenticatedAuthenticatedRouteImport } from './routes/(authenticated)/_authenticated'
import { Route as authenticatedAuthenticatedPerfilRouteImport } from './routes/(authenticated)/_authenticated/perfil'
import { Route as authenticatedAuthenticatedDashboardRouteImport } from './routes/(authenticated)/_authenticated/dashboard'
import { Route as authenticatedAuthenticatedUsuariosIndexRouteImport } from './routes/(authenticated)/_authenticated/usuarios/index'
import { Route as authenticatedAuthenticatedHospedesIndexRouteImport } from './routes/(authenticated)/_authenticated/hospedes/index'
import { Route as authenticatedAuthenticatedFlatsIndexRouteImport } from './routes/(authenticated)/_authenticated/flats/index'
import { Route as authenticatedAuthenticatedCategoriasIndexRouteImport } from './routes/(authenticated)/_authenticated/categorias/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const publicLoginRoute = publicLoginRouteImport.update({
  id: '/(public)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const authenticatedAuthenticatedRoute =
  authenticatedAuthenticatedRouteImport.update({
    id: '/(authenticated)/_authenticated',
    getParentRoute: () => rootRouteImport,
  } as any)
const authenticatedAuthenticatedPerfilRoute =
  authenticatedAuthenticatedPerfilRouteImport.update({
    id: '/perfil',
    path: '/perfil',
    getParentRoute: () => authenticatedAuthenticatedRoute,
  } as any)
const authenticatedAuthenticatedDashboardRoute =
  authenticatedAuthenticatedDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => authenticatedAuthenticatedRoute,
  } as any)
const authenticatedAuthenticatedUsuariosIndexRoute =
  authenticatedAuthenticatedUsuariosIndexRouteImport.update({
    id: '/usuarios/',
    path: '/usuarios/',
    getParentRoute: () => authenticatedAuthenticatedRoute,
  } as any)
const authenticatedAuthenticatedHospedesIndexRoute =
  authenticatedAuthenticatedHospedesIndexRouteImport.update({
    id: '/hospedes/',
    path: '/hospedes/',
    getParentRoute: () => authenticatedAuthenticatedRoute,
  } as any)
const authenticatedAuthenticatedFlatsIndexRoute =
  authenticatedAuthenticatedFlatsIndexRouteImport.update({
    id: '/flats/',
    path: '/flats/',
    getParentRoute: () => authenticatedAuthenticatedRoute,
  } as any)
const authenticatedAuthenticatedCategoriasIndexRoute =
  authenticatedAuthenticatedCategoriasIndexRouteImport.update({
    id: '/categorias/',
    path: '/categorias/',
    getParentRoute: () => authenticatedAuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof publicLoginRoute
  '/dashboard': typeof authenticatedAuthenticatedDashboardRoute
  '/perfil': typeof authenticatedAuthenticatedPerfilRoute
  '/categorias/': typeof authenticatedAuthenticatedCategoriasIndexRoute
  '/flats/': typeof authenticatedAuthenticatedFlatsIndexRoute
  '/hospedes/': typeof authenticatedAuthenticatedHospedesIndexRoute
  '/usuarios/': typeof authenticatedAuthenticatedUsuariosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof publicLoginRoute
  '/dashboard': typeof authenticatedAuthenticatedDashboardRoute
  '/perfil': typeof authenticatedAuthenticatedPerfilRoute
  '/categorias': typeof authenticatedAuthenticatedCategoriasIndexRoute
  '/flats': typeof authenticatedAuthenticatedFlatsIndexRoute
  '/hospedes': typeof authenticatedAuthenticatedHospedesIndexRoute
  '/usuarios': typeof authenticatedAuthenticatedUsuariosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(authenticated)/_authenticated': typeof authenticatedAuthenticatedRouteWithChildren
  '/(public)/login': typeof publicLoginRoute
  '/(authenticated)/_authenticated/dashboard': typeof authenticatedAuthenticatedDashboardRoute
  '/(authenticated)/_authenticated/perfil': typeof authenticatedAuthenticatedPerfilRoute
  '/(authenticated)/_authenticated/categorias/': typeof authenticatedAuthenticatedCategoriasIndexRoute
  '/(authenticated)/_authenticated/flats/': typeof authenticatedAuthenticatedFlatsIndexRoute
  '/(authenticated)/_authenticated/hospedes/': typeof authenticatedAuthenticatedHospedesIndexRoute
  '/(authenticated)/_authenticated/usuarios/': typeof authenticatedAuthenticatedUsuariosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/perfil'
    | '/categorias/'
    | '/flats/'
    | '/hospedes/'
    | '/usuarios/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/perfil'
    | '/categorias'
    | '/flats'
    | '/hospedes'
    | '/usuarios'
  id:
    | '__root__'
    | '/'
    | '/(authenticated)/_authenticated'
    | '/(public)/login'
    | '/(authenticated)/_authenticated/dashboard'
    | '/(authenticated)/_authenticated/perfil'
    | '/(authenticated)/_authenticated/categorias/'
    | '/(authenticated)/_authenticated/flats/'
    | '/(authenticated)/_authenticated/hospedes/'
    | '/(authenticated)/_authenticated/usuarios/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authenticatedAuthenticatedRoute: typeof authenticatedAuthenticatedRouteWithChildren
  publicLoginRoute: typeof publicLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/login': {
      id: '/(public)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof publicLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authenticated)/_authenticated': {
      id: '/(authenticated)/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authenticatedAuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authenticated)/_authenticated/perfil': {
      id: '/(authenticated)/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof authenticatedAuthenticatedPerfilRouteImport
      parentRoute: typeof authenticatedAuthenticatedRoute
    }
    '/(authenticated)/_authenticated/dashboard': {
      id: '/(authenticated)/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof authenticatedAuthenticatedDashboardRouteImport
      parentRoute: typeof authenticatedAuthenticatedRoute
    }
    '/(authenticated)/_authenticated/usuarios/': {
      id: '/(authenticated)/_authenticated/usuarios/'
      path: '/usuarios'
      fullPath: '/usuarios/'
      preLoaderRoute: typeof authenticatedAuthenticatedUsuariosIndexRouteImport
      parentRoute: typeof authenticatedAuthenticatedRoute
    }
    '/(authenticated)/_authenticated/hospedes/': {
      id: '/(authenticated)/_authenticated/hospedes/'
      path: '/hospedes'
      fullPath: '/hospedes/'
      preLoaderRoute: typeof authenticatedAuthenticatedHospedesIndexRouteImport
      parentRoute: typeof authenticatedAuthenticatedRoute
    }
    '/(authenticated)/_authenticated/flats/': {
      id: '/(authenticated)/_authenticated/flats/'
      path: '/flats'
      fullPath: '/flats/'
      preLoaderRoute: typeof authenticatedAuthenticatedFlatsIndexRouteImport
      parentRoute: typeof authenticatedAuthenticatedRoute
    }
    '/(authenticated)/_authenticated/categorias/': {
      id: '/(authenticated)/_authenticated/categorias/'
      path: '/categorias'
      fullPath: '/categorias/'
      preLoaderRoute: typeof authenticatedAuthenticatedCategoriasIndexRouteImport
      parentRoute: typeof authenticatedAuthenticatedRoute
    }
  }
}

interface authenticatedAuthenticatedRouteChildren {
  authenticatedAuthenticatedDashboardRoute: typeof authenticatedAuthenticatedDashboardRoute
  authenticatedAuthenticatedPerfilRoute: typeof authenticatedAuthenticatedPerfilRoute
  authenticatedAuthenticatedCategoriasIndexRoute: typeof authenticatedAuthenticatedCategoriasIndexRoute
  authenticatedAuthenticatedFlatsIndexRoute: typeof authenticatedAuthenticatedFlatsIndexRoute
  authenticatedAuthenticatedHospedesIndexRoute: typeof authenticatedAuthenticatedHospedesIndexRoute
  authenticatedAuthenticatedUsuariosIndexRoute: typeof authenticatedAuthenticatedUsuariosIndexRoute
}

const authenticatedAuthenticatedRouteChildren: authenticatedAuthenticatedRouteChildren =
  {
    authenticatedAuthenticatedDashboardRoute:
      authenticatedAuthenticatedDashboardRoute,
    authenticatedAuthenticatedPerfilRoute:
      authenticatedAuthenticatedPerfilRoute,
    authenticatedAuthenticatedCategoriasIndexRoute:
      authenticatedAuthenticatedCategoriasIndexRoute,
    authenticatedAuthenticatedFlatsIndexRoute:
      authenticatedAuthenticatedFlatsIndexRoute,
    authenticatedAuthenticatedHospedesIndexRoute:
      authenticatedAuthenticatedHospedesIndexRoute,
    authenticatedAuthenticatedUsuariosIndexRoute:
      authenticatedAuthenticatedUsuariosIndexRoute,
  }

const authenticatedAuthenticatedRouteWithChildren =
  authenticatedAuthenticatedRoute._addFileChildren(
    authenticatedAuthenticatedRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authenticatedAuthenticatedRoute: authenticatedAuthenticatedRouteWithChildren,
  publicLoginRoute: publicLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
